### ISSUE TITLE
esp32 secure websocket using ssl (WSS)

### ISSUE THREAD

**Issue by meakash** [SIMS-IOT-Devices/FreeRTOS-ESP-IDF-WebSockets-Server#2]
Hello, thank you for the great Explanation on youtube.

I wanted to have Secure Websockets over SSL.

Could you help me to get started as to how can I modify the server example.

PS: This is a feature request, not a bug.

**Comment by SIMS-IOT-Devices** [comment]
Dear meakash,
I have updated this request in the future wish list. Others also requested it.
Hope will get to it in the near future.

**Comment by meakashrao** [comment]
Thank You

**Comment by meakash** [comment]
Thank you for the prompt response
